GET http://localhost:3000/?a=42&b=10
Content-Type: application/json
###

Post http://localhost:3000/getSum
Content-Type: application/json 

{

"a": "98",
"b": "71"

}

###

# 2 usuless request deleted
